services:
  consul:
    image: consul:1.15.4
    container_name: dev-consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0

  sim-service:
    build:
      context: .
      dockerfile: sim-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - consul
