// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: sim.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimService_GetNodes_FullMethodName = "/sim.SimService/GetNodes"
)

// SimServiceClient is the client API for SimService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimServiceClient interface {
	GetNodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodesResponse, error)
}

type simServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimServiceClient(cc grpc.ClientConnInterface) SimServiceClient {
	return &simServiceClient{cc}
}

func (c *simServiceClient) GetNodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodesResponse)
	err := c.cc.Invoke(ctx, SimService_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimServiceServer is the server API for SimService service.
// All implementations must embed UnimplementedSimServiceServer
// for forward compatibility.
type SimServiceServer interface {
	GetNodes(context.Context, *Empty) (*NodesResponse, error)
	mustEmbedUnimplementedSimServiceServer()
}

// UnimplementedSimServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimServiceServer struct{}

func (UnimplementedSimServiceServer) GetNodes(context.Context, *Empty) (*NodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedSimServiceServer) mustEmbedUnimplementedSimServiceServer() {}
func (UnimplementedSimServiceServer) testEmbeddedByValue()                    {}

// UnsafeSimServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimServiceServer will
// result in compilation errors.
type UnsafeSimServiceServer interface {
	mustEmbedUnimplementedSimServiceServer()
}

func RegisterSimServiceServer(s grpc.ServiceRegistrar, srv SimServiceServer) {
	// If the following call pancis, it indicates UnimplementedSimServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimService_ServiceDesc, srv)
}

func _SimService_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimServiceServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimService_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimServiceServer).GetNodes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SimService_ServiceDesc is the grpc.ServiceDesc for SimService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sim.SimService",
	HandlerType: (*SimServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodes",
			Handler:    _SimService_GetNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sim.proto",
}
